# Generated by Django 6.0.4 on 2026-05-04 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "collection log",
                "verbose_name_plural": "collection logs",
            },
        ),
    ]
