from django.utils.translation import gettext_lazy as _

RANKINGS = [
    {
        "id": "hours",
        "field": "play_time_ticks",
        "label": _("Hours Played"),
        "icon": "⏱️",
        "icon_img": "rankings/images/timer.png",
        "format": "hours",
        "webhook_env": "DISCORD_WEBHOOK_HOURS",
    },
    {
        "id": "catches",
        "field": "pokemons_caught",
        "label": _("Pokémons Caught"),
        "icon": "🔴",
        "icon_img": "rankings/images/pokeball_icon.svg",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_CATCHES",
    },
    {
        "id": "pokedex",
        "field": "pokedex_registered",
        "label": _("Pokédex Registered"),
        "icon": "📕",
        "icon_img": "rankings/images/pokedex_icon.png",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_POKEDEX",
    },
    {
        "id": "battles",
        "field": "battles_won",
        "label": _("Battles Won"),
        "icon": "⚔️",
        "icon_img": "rankings/images/battle_icon.png",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_BATTLES",
    },
    {
        "id": "money",
        "field": "cobbledollars",
        "label": _("CobbleDollars"),
        "icon": "💰",
        "icon_img": "rankings/images/pokecoin.png",
        "format": "currency",
        "webhook_env": "DISCORD_WEBHOOK_MONEY",
    },
    {
        "id": "deaths",
        "field": "deaths",
        "label": _("Deaths"),
        "icon": "💀",
        "icon_img": "rankings/images/ranking_icon.png",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_DEATHS",
    },
    {
        "id": "distance",
        "field": "distance_cm",
        "label": _("Distance Traveled"),
        "icon": "🧭",
        "icon_img": "rankings/images/ranking_icon.png",
        "format": "km",
        "webhook_env": "DISCORD_WEBHOOK_DISTANCE",
    },
    {
        "id": "pokeballs",
        "field": "pokeballs_thrown",
        "label": _("Poké Balls Thrown"),
        "icon": "🎯",
        "icon_img": "rankings/images/ranking_icon.png",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_POKEBALLS",
    },
]
