from django.utils.translation import gettext_lazy as _

RANKINGS = [
    {
        "id": "hours",
        "field": "play_time_ticks",
        "label": _("Hours Played"),
        "icon": "⏱️",
        "icon_img": "rankings/images/timer.png",
        "format": "hours",
        "webhook_env": "DISCORD_WEBHOOK_HOURS",
    },
    {
        "id": "catches",
        "field": "pokemons_caught",
        "label": _("Pokémons Caught"),
        "icon": "🔴",
        "icon_img": "rankings/images/pokeball_icon.svg",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_CATCHES",
    },
    {
        "id": "pokedex",
        "field": "pokedex_registered",
        "label": _("Pokédex Registered"),
        "icon": "📕",
        "icon_img": "rankings/images/pokedex_icon.png",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_POKEDEX",
    },
    {
        "id": "cards",
        "field": "cobbletcg_cards",
        "label": _("CobbleTCG Cards"),
        "icon": "🃏",
        "icon_img": "rankings/images/tcg_icon.jpg",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_CARDS",
    },
    {
        "id": "battles",
        "field": "battles_won",
        "label": _("Battles Won"),
        "icon": "⚔️",
        "icon_img": "rankings/images/battle_icon.png",
        "format": "number",
        "webhook_env": "DISCORD_WEBHOOK_BATTLES",
    },
    {
        "id": "money",
        "field": "cobbledollars",
        "label": _("CobbleDollars"),
        "icon": "💰",
        "icon_img": "rankings/images/pokecoin.png",
        "format": "currency",
        "webhook_env": "DISCORD_WEBHOOK_MONEY",
    },
]
