# Generated by Django 6.0.4 on 2026-05-04 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wikipage",
            options={
                "ordering": ["title"],
                "verbose_name": "wiki page",
                "verbose_name_plural": "wiki pages",
            },
        ),
    ]
