# Generated by Django 6.0.4 on 2026-05-04 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discord_notifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discordpostedmessage",
            options={
                "ordering": ["ranking_id"],
                "verbose_name": "discord posted message",
                "verbose_name_plural": "discord posted messages",
            },
        ),
    ]
