# Generated by Django 6.0.4 on 2026-05-04 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["username"],
                "verbose_name": "player",
                "verbose_name_plural": "players",
            },
        ),
        migrations.AlterModelOptions(
            name="playerstats",
            options={
                "ordering": ["player__username"],
                "verbose_name": "player stats",
                "verbose_name_plural": "player stats",
            },
        ),
    ]
