# Generated by Django 6.0.4 on 2026-06-02 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_alter_player_options_alter_playerstats_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstats",
            name="cobbletcg_cards",
        ),
    ]
