# Generated by Django 6.0.4 on 2026-06-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_remove_playerstats_cobbletcg_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstats",
            name="deaths",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="distance_cm",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="pokeballs_thrown",
            field=models.IntegerField(default=0),
        ),
    ]
