# Generated by Django 6.0.4 on 2026-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0004_playerstats_deaths_playerstats_distance_cm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hide this player from public rankings (e.g. admin accounts).",
            ),
        ),
    ]
