# Generated by Django 6.0.4 on 2026-05-04 17:06

import features.mods.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("description_pt_br", models.TextField(blank=True)),
                ("mod_url", models.URLField()),
                ("mod_wiki", models.URLField(blank=True)),
                ("dependencies", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(default=list)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("server-side", "Server-Side"),
                            ("client-side", "Client-Side"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=features.mods.models._thumbnail_upload_path,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mod",
                "verbose_name_plural": "Mods",
                "ordering": ["name"],
            },
        ),
    ]
