# Generated by Django 6.0.4 on 2026-05-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mod",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
